# Generated by Django 5.1.5 on 2025-01-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artigo', '0002_alter_artigo_table'),
        ('etapas', '0001_initial'),
        ('usuario', '0008_remove_usuario_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreabilidade',
            fields=[
                ('codigo_rastreio', models.AutoField(primary_key=True, serialize=False)),
                ('data_incio', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('falha', models.BooleanField(default=False)),
                ('data_fim', models.DateField()),
                ('codigo_artigo', models.ForeignKey(db_column='codigo_artigo', on_delete=django.db.models.deletion.CASCADE, to='artigo.artigo')),
                ('codigo_etapa', models.ForeignKey(db_column='codigo_etapa', on_delete=django.db.models.deletion.CASCADE, to='etapas.etapa')),
                ('codigo_usuario', models.ForeignKey(db_column='codigo_user', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
