# Generated by Django 5.1.5 on 2025-01-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papel', '0001_initial'),
        ('usuario', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Papel',
            new_name='Papeis',
        ),
        migrations.AlterModelTable(
            name='papeis',
            table='papeis',
        ),
    ]
