# Generated by Django 5.1.5 on 2025-01-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papel', '0002_rename_papel_papeis_alter_papeis_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papeis',
            name='id',
        ),
        migrations.AddField(
            model_name='papeis',
            name='codigo_papel',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papeis',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
