# Generated by Django 5.1.5 on 2025-01-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('codigo_perm', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permissao',
            },
        ),
    ]
