# Generated by Django 5.1.5 on 2025-01-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha_hash',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='papel',
            new_name='role_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
    ]
