# Generated by Django 5.1.5 on 2025-01-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_senha_hash_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
