# Generated by Django 5.1.5 on 2025-01-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_password_usuario_passwordhash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='role_id',
            new_name='codigo_papel',
        ),
    ]
