# Generated by Django 5.1.5 on 2025-01-24 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papel', '0003_remove_papeis_id_papeis_codigo_papel_and_more'),
        ('usuario', '0005_rename_role_id_usuario_codigo_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_papel',
            field=models.ForeignKey(db_column='codigo_papel', on_delete=django.db.models.deletion.CASCADE, to='papel.papeis'),
        ),
    ]
