# Generated by Django 5.1.5 on 2025-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_codigo_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
