# Generated by Django 5.1.5 on 2025-01-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
    ]
