# Generated by Django 5.1.5 on 2025-01-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papel', '0003_remove_papeis_id_papeis_codigo_papel_and_more'),
        ('permissao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapelPermissao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_papel', models.ForeignKey(db_column='codigo_papel', on_delete=django.db.models.deletion.CASCADE, to='papel.papeis')),
                ('codigo_perm', models.ForeignKey(db_column='codigo_perm', on_delete=django.db.models.deletion.CASCADE, to='permissao.permissao')),
            ],
        ),
    ]
