# Generated by Django 5.1.5 on 2025-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('codigo_artigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo_material', models.CharField(max_length=250)),
                ('data_validate', models.DateField()),
                ('codigo_serial', models.CharField(max_length=288)),
            ],
        ),
    ]
