# Generated by Django 5.1.5 on 2025-01-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artigo',
            table='artigo',
        ),
    ]
